### ISSUE TITLE
"eventNameWindowEventMessage" not exported

### ISSUE THREAD

**Issue by DesWurstes** [OpenBazaar/spvwallet#31]
"eventNameWindowEventMessage" not exported

[Spvwallet code](https://github.com/OpenBazaar/spvwallet/blob/master/gui/bootstrap/run.go#L72)

[Go astilectron code](https://github.com/asticode/go-astilectron/blame/master/window.go#L40)

[commit](https://github.com/asticode/go-astilectron/commit/9e21990f582d7ed1654fe885547570fad1880fcd#diff-0843e716034a3d8598760bcf3a0b51deR40)

The second error I got is this:
```
w.Send undefined (type *astilectron.Window has no field or method Send)
```
[Spvwallet code](https://github.com/OpenBazaar/spvwallet/blob/master/gui/bootstrap/run.go#L92)

[Go Astilectron code](https://github.com/asticode/go-astilectron/blob/master/window.go#L362)

[commit](https://github.com/asticode/go-astilectron/commit/9e21990f582d7ed1654fe885547570fad1880fcd#diff-0843e716034a3d8598760bcf3a0b51deL328)

The second error is easy to fix: replace all "Send"s with SendMessage

**Comment by annjieching** [comment]
hi there, how would you suggest fixing the first error? not quite sure where to start. tried git checkout on the astilectron code with commit hash but it said 'reference is not a tree'. thanks!

**Comment by DesWurstes** [comment]
Download it from here: https://github.com/asticode/go-astilectron/archive/v0.5.0.zip
