### ISSUE TITLE
Does this work with Bitcoin Cash (Bitcoin ABC)?

### ISSUE THREAD

**Issue by BubbaJoe** [OpenBazaar/spvwallet#48]

**Comment by placer14** [comment]
No, you want https://github.com/cpacia/BitcoinCash-Wallet

**Comment by BubbaJoe** [comment]
https://github.com/BubbaJoe/BitcoinCash-Wallet

Recommend any one else who sees this to use my new repo which uses gcash's bchd instead of btcsuite's btcd. Thanks!
