### ISSUE TITLE
Handle tx reject

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/spvwallet#5]
Received this when sending a transaction: `[incomingMessageHandler] [WARNING] Rejected! cmd: tx code: REJECT_INSUFFICIENTFEE tx`

1) This should not happen as it suggests the fee code isn't working right. 
2) Need to handle this message and either don't commit the tx to the database or use rbf.

**Comment by cpacia** [comment]
The fee part is fixed but it should still handled rejects.

**Comment by hoffmabc** [comment]
What's the status on this one? It's like 5 months old.
